package com.peihua.chartline

sealed class LineChartRoute(val value: String) {
    object Splash : LineChartRoute("Screen")
    object Main : LineChartRoute("Main")
    object Quote : LineChartRoute("Quote")
    object MpChart : LineChartRoute("MpChart")
    object LineChart : LineChartRoute("LineChart")
    object BarChart: LineChartRoute("BarChart")
    object PieChart: LineChartRoute("PieChart")
    object AAChartCore: LineChartRoute("AAChartCore")
    object AALineChart: LineChartRoute("AALineChart")
    object AAColumnChart: LineChartRoute("AAColumnChart")
    object AABarChart: LineChartRoute("AABarChart")
    object AnyChart: LineChartRoute("AnyChart")
    object AnyChartLine: LineChartRoute("AnyChartLine")
    object AnyChartColumn: LineChartRoute("AnyChartColumn")
    object AnyChartBar: LineChartRoute("AnyChartBar")
    object HdCharts: LineChartRoute("HdCharts")
    object HdChartsLine: LineChartRoute("HdChartsLine")
    object HdChartsColumn: LineChartRoute("HdChartsColumn")
    object HdChartsBar: LineChartRoute("HdChartsBar")
    object HdChartsRadar: LineChartRoute("HdChartsRadar")
    object VicoCharts: LineChartRoute("VicoCharts")
    object VicoChartsLine: LineChartRoute("VicoChartsLine")
    object VicoChartsColumn: LineChartRoute("VicoChartsColumn")
    object VicoChartsRadar: LineChartRoute("VicoChartsRadar")
    object VicoChartsCombo: LineChartRoute("VicoChartsCombo")
    object Charty: LineChartRoute("Charty")
    object ChartyLine: LineChartRoute("ChartyLine")
    object ChartyBar: LineChartRoute("ChartyBar")
    object ChartyColumn: LineChartRoute("ChartyColumn")
    object ChartyRadar: LineChartRoute("ChartyRadar")
    object ChartyCombo: LineChartRoute("ChartyCombo")
    object YCharts: LineChartRoute("YCharts")
    object YChartsLine: LineChartRoute("YChartsLine")
    object YChartsBar: LineChartRoute("YChartsBar")
    object YChartsColumn: LineChartRoute("YChartsColumn")
    object YChartsRadar: LineChartRoute("YChartsRadar")
    object YChartsCombo: LineChartRoute("YChartsCombo")
    object ComposeCharts: LineChartRoute("ComposeCharts")
    object ComposeChartsLine: LineChartRoute("ComposeChartsLine")
    object ComposeChartsBar: LineChartRoute("ComposeChartsBar")
    object ComposeChartsColumn: LineChartRoute("ComposeChartsColumn")
    object ComposeChartsRadar: LineChartRoute("ComposeChartsRadar")
    object ComposeChartsCombo: LineChartRoute("ComposeChartsCombo")
    object AAYChart: LineChartRoute("AAYChart")
    object AAYChartLine: LineChartRoute("AAYLineChart")
    object AAYChartColumn: LineChartRoute("AAYColumnChart")
    object AAYChartBar: LineChartRoute("AAYBarChart")
    object AAYChartRadar: LineChartRoute("AAYRadarChart")
    object AAYChartCombo: LineChartRoute("AAYComboChart")
}